name: Convert README to PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Install pandoc and texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra texlive-xetex

      - name: Convert README to PDF
        run: |
          pandoc README.md -o README.pdf --pdf-engine=xelatex -V geometry:"top=2cm, bottom=2cm, left=2cm, right=2cm" -V colorlinks=true -V linkcolor=blue -V urlcolor=blue -V toccolor=gray

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: FSAF_Report
          path: README.pdf

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Update PDF version of README" -a || exit 0
          git push origin HEAD:${GITHUB_REF#refs/heads/}
