name: Convert README to PDF

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation
          npm install -g md-to-pdf

      - name: Convert README to PDF
        run: |
          md-to-pdf README.md --config-file pdf-config.json

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: FSAF_Report
          path: README.pdf

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.pdf
          git commit -m "Update PDF version of README" -a || exit 0
          git push origin HEAD:${GITHUB_REF#refs/heads/}
